### ISSUE TITLE
GtkStackPage is not GtkBuildable

### ISSUE THREAD

**Issue by eminfedar** [sonnyp/Workbench#137] opened 2022-07-15 11:06 UTC
I want to design a stack page in Gtk4.

But it gives this error:
```
(re.sonny.Workbench:4): Workbench-CRITICAL **: 14:01:50.766: GtkStackPage is not a GtkBuildable
```

The example Blueprint:
```
using Gtk 4.0;

Stack {
  StackPage {
    name: "page1";
    child: Label {
      label: "test";
    };
  }
  StackPage {
    name: "page2";
    child: Label {
      label: "test";
    };
  }
}
```
But I can do it in XML like this and it gives no error when using with GtkBuilder:
```
<object class="GtkStack" id="stack1">
    <child>
        <object class="GtkStackPage">
            <property name="name">page1</property>
            <property name="child">
                <object class="GtkLabel">
                    <property name="label">test</property>
                </object>
            </property>
        </object>
    </child>
    <child>
        <object class="GtkStackPage">
            <property name="name">page2</property>
            <property name="child">
                <object class="GtkLabel">
                    <property name="label">test</property>
                </object>
            </property>
        </object>
    </child>
</object>
```

**Comment by sonnyp** [comment] 2022-07-15 16:42
Thanks for the clear report.

It's a duplicate of https://github.com/sonnyp/Workbench/issues/135

Fixed in https://github.com/sonnyp/Workbench/pull/136

You can build Workbench easily with GNOME Builder or just wait for the next release -I'll try to take care of it over the weekend.

**Closed** 2022-07-15 16:47 UTC
