### ISSUE TITLE
Popover appears and instantly disappears on hovering above warnings

### ISSUE THREAD

**Issue by RocketRide9** [sonnyp/Workbench#467] opened 2023-08-02 12:28 UTC
Popover appears and instantly disappears on hovering above warnings.
Also 
```
(re.sonny.Workbench:4): Gtk-CRITICAL **: 19:26:25.979: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed
```
shows in console.

**Comment by RocketRide9** [comment] 2023-08-02 12:35
[Kooha-2023-08-02-19-31-19.webm](https://github.com/sonnyp/Workbench/assets/70429241/12064a41-d2cd-4885-a6b2-12c5a4763d06)

**Comment by sonnyp** [comment] 2023-08-02 12:38
Duplicate of https://github.com/sonnyp/Workbench/issues/179

**Closed by sonnyp** 2023-08-02 12:38 UTC
